version: '3.9'

services:
  postgres:
    container_name: postgres
    image: "postgres:alpine"
    restart: on-failure
    ports:
      - "5432:5432"
    env_file: ./docker/postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - go-coding-challenge

  user-service:
    image: go-coding-challenge/user-service
    container_name: user-service
    # restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:9090' # gRPC server
      - '8000:8000' # gRPC gateway
    command: ["-c","./service/user/config.yml","user-service"]
    networks:
      - go-coding-challenge
    depends_on:
      - postgres

networks:
  go-coding-challenge:

volumes:
  postgres: