serviceName: "service.user"
version: "v1"
grpc:
  host: "user-service"
  port: 9090
  max-call-recv-msg-size: 0
  max-call-send-msg-size: 0
proxy:
  port: 8000
jwt:
  secretKey: "lu"
  duration: "1200s"
  issuer: "lu"
# redis:
#   nodes:
#     - "host.docker.internal:6379"
#     - "redis:6379"
#   prefix: "user-service"
database:
  host: "postgres"
  port: 5432
  user:  "root"
  password: "root"
  scheme: "users"
  maxIdleConns: 10
  maxOpenConns: 100
  connectTimeout: "1h"
  debug: true
enableTLS: false
TLSCert:
  CACert : "./cert/ca-cert.pem"
  CertPem: "./cert/server-cert.pem"
  KeyPem : "./cert/server-key.pem"
log:
  #PANNIC, FATAL, ERROR, WARN, INFO, DEBUG
  mode: "dev"
  level: "DEBUG"
  levelTrace: "FATAL"
clientConfig:
  account:
    serviceName: "service.account"
    version: "v1"
    grpc: 
      host: "account-service"
      port: 9090
    enableTLS: false
    TLSCert:
      CACert : "./cert/ca-cert.pem"
  transaction:
    serviceName: "service.transaction"
    version: "v1"
    grpc: 
      host: "transaction-service"
      port: 9090
    enableTLS: false