serviceName: "user-client-service"
version: "v1"
enableTracing: false
tracing:
  metrics: "prometheus"
clientConfig:
  user:
    serviceName: "service.user"
    version: "v1"
    enableTracing: false
    grpc: 
      host: "user-service"
      port: 9090
    enableTLS: false
    TLSCert:
      CACert : "./cert/ca-cert.pem"
log:
  #PANNIC, FATAL, ERROR, WARN, INFO, DEBUG
  mode: "dev"
  level: "DEBUG"
  levelTrace: "FATAL"
  isLogFile: false
  pathLogFile: "./logFile.log"